// This file was generated by Prisma and has been updated for Prisma v7.
// It configures a local SQLite datasource for the inventory package.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    adapter: "sqlite",
    url: "file:./dev.db",
  },
});
